// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import store from "@/redux";
import ProviderComp from "@/redux/provide";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <ProviderComp>
          <Suspense fallback={<p>Loading</p>}>
            {children}
            <Toaster position="bottom-right" />
          </Suspense>
        </ProviderComp>
      </body>
    </html>
  );
}
